name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - root=6.32.08
  - pip
  - pip:
      - correctionlib
      - distributed==2025.1.0
      - dask_gateway==2024.1.0
      - matplotlib